### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jinxedau** [flightcrank/JRatioBoost#1]
I get the following error

![error](https://user-images.githubusercontent.com/54124744/63064316-df34bc00-bf43-11e9-91df-b0d1543c2b61.jpg)

**Comment by flightcrank** [comment]
I just checked and can confirm that JRatioBoost is working fine with torrentleech on my end. As I am also a member there.

try changing the tracker by using the right-click popup menu. And check if that torrent has a second tracker url in it.

could be a problem with your ISP ? maybe try some other trackers aswell and see if they work.

**Comment by jinxedau** [comment]
Tried setting there is , and i end up with the same error.

**Comment by flightcrank** [comment]
I cant seem to reproduce that error as torrent leech works fine for me.

Does the program work with other torrent trackers ?
Can you connect to the tracker with a regular torrent client (utorrent etc) ?

I think it may be a problem with your ISP or Internet setup.

Ill do some research and see what i can find out.

**Comment by jinxedau** [comment]
Yes I am able to connect and download without any problems with utorrent .
I was using mratio fine until this week. Now it just times out all the time.
I was thinking maybe torrentleech had changed some settings.

**Comment by flightcrank** [comment]
perhaps have a look at java security settings. on windows 

https://java.com/en/download/help/win_controlpanel.xml

 Or use a newer version of java like java 11.

I can confirm it is working fine on linux under java 8 and java 11. Ill try and install windows and test on there when i get time.

**Comment by jinxedau** [comment]
I’ll try your recommendations when I get home and let you know how I go.
Cheers
Paul

**Comment by jinxedau** [comment]
Feel like a idiot , last place to check was my problem.
My vpn stupid me 0_o
