### ISSUE TITLE
feature needed : enabled drag and drop torrents .

### ISSUE THREAD

**Issue by mmmmm-sbi** [flightcrank/JRatioBoost#14]
feature needed : enabled drag and drop torrents .

**Comment by flightcrank** [comment]
I don't really agree this is a needed feature. The program supports multiple arguments from the command line, as well as multiple file selection from the open file dialog. Its trivial to open many torrents at once using these methods. supporting drag and drop is pretty redundant.

**Comment by mmmmm-sbi** [comment]
the easiest way to me is drag the torrent and drop .

**Comment by flightcrank** [comment]
point taken. ill implement this feature if enough users demand it.
