### ISSUE TITLE
feature needed : currently i can only seed but i need downloading also.

### ISSUE THREAD

**Issue by mmmmm-sbi** [flightcrank/JRatioBoost#15]
feature needed : currently i can only seed but i need downloading also.

**Comment by flightcrank** [comment]
Download spoofing is still in the program, but was removed from the GUI. As its not really needed. Just download legitimately, then spoof your uploads. Its the whole reason why the program was made. Cross seeding is allowed on pretty much every private torrent tracker. The program reports that the whole file has already been 100% downloaded. If any one really wants it that badly, its already implemented. Just need to modify the GUI to add it in. I can provide a .form file for the GUI that will work with the NetBeans IDE if any one needs it.
