### ISSUE TITLE
Feature request to stop uploading when leecher is 0

### ISSUE THREAD

**Issue by hoonlight** [flightcrank/JRatioBoost#16]
Hi, first of all thanks for making such a good program.

Wouldn't it be nice to have the ability for JRatioBoost to stop uploading those torrents when leecher is not present? 
I'm worried that the tracker will detect it as abnormal uploading.

**Comment by flightcrank** [comment]
well if your uploading then there is always a leecher, because you will be counted as one. I think you mean to stop uploading when seeders is at 0. which makes sense. ill see what i can do.
