### ISSUE TITLE
[Not a Issue] [Feature Request]

### ISSUE THREAD

**Issue by uNbAs** [flightcrank/JRatioBoost#3]
Its possible integrate with transmission and run with headless and use real torrents avaible in transmission?

**Comment by flightcrank** [comment]
well its coded in java while Transmission is c or c++. so couldn't really integrate the two. I could include a feature where you could load up more than one torrent and spoof them all at the same time however. that way you could just load up the same torrents you have in Transmission in JRatioBoost.

**Comment by uNbAs** [comment]
Its a good idea, too its possible obtain outputlog from console?
I ask this for check total of upload KB and stop the torrent and not have excessive ratio

**Comment by uNbAs** [comment]
Seems like a good idea to be able to select multiple torrent.

I would like, if it were possible to run it in headless mode to be able to use it from a console.

If possible I would also like to select the total upload I want to get for each torrent, or at least get some data through the console to be able to make a script that does start / stop when necessary.
