### ISSUE TITLE
403 ERROR

### ISSUE THREAD

**Issue by leonard4546** [flightcrank/JRatioBoost#4]
Not working it's giving error.
Server respond HTTPS error 403.

**Comment by flightcrank** [comment]
Cool that means it it working, the tracker is blocking it for some reason. Which tracker is it ill see if i can update it to work with it.

**Comment by leonard4546** [comment]
I tried on some other trackers. It worked on one tracker. And in other two it's giving error : " this client is banned" .
I changed client using client option. But still same problem.

**Comment by flightcrank** [comment]
ok, let me know what trackers and ill join up and see if i can solve the issue.

**Comment by leonard4546** [comment]
avistaz.to this one. It gives error: This client is banned.
Maybe useragent or client change will fix that.
And thank you for this. It's working on all major trackers.

**Comment by flightcrank** [comment]
bummer its invite only. you can shoot me an invite if you got one. Your probably right about the user agent. You could also try changing the client version number, which there is a menu item for if you right click. Its some Asian tracker so who knows what client they want, probably some client with a backdoor for the CCP lol.

im basically 100% sure i could get it working but no way to know if i cant test it. It is open source so you can have a go yourself and push the changes and ill commit them.

**Comment by leonard4546** [comment]
I don't have invite bcoz I'm new member. But i can send active Torrent if you want. Is there any way to send that?

**Comment by flightcrank** [comment]
bad idea, because the torrent has your unique passkey. Could get you banned as it will show the torrent coming form 2 different IP's. Just wait till you get an invite. Cant do much in the meantime.

**Comment by leonard4546** [comment]
It's my spare account 😅

**Comment by flightcrank** [comment]
well if your cool with it you can send it or a link to it to ocaumaxim at gmail dot com

**Comment by flightcrank** [comment]
well avistaz.to seems to be working now. It was the user agent. Can't confirm if it fixes myanonamouse.net as well so you'll have to check that.

let me know if it work ok on your end.

**Comment by leonard4546** [comment]
Thanks Bro. It's working on avistaz and now also working on some other trackers. And for myanonmous update interval is almost 1 DAY so i will inform after that.

Is there any way to change interval. I tried using right click and not working.

**Comment by flightcrank** [comment]
thats cool that its working now.

As for the update interval. It seems to be working fine on my end. When the interval reaches zero thats when the program sends the fake upload amount to the tracker. The tracker then sends back how many seconds it wants to have passed before it wants another update. This defaults to 1800 seconds which is 30 minutes on most trackers. So the update amount is determined by the tracker, i just allowed a feature to override it. but it will resort to the trackers preferred amount every time it reaches 0.

anyway since this issue is fixed ill close it, thanks for the feedback.
