### ISSUE TITLE
[Request]Android Ratio Booster[Not an issue]

### ISSUE THREAD

**Issue by KZTanvir** [flightcrank/JRatioBoost#6]
Is there any android versions of this program you made.
I heared about it in a website.
Long time desktop using is a problem and there are some trackers that doesnt like (actually ban)
users using boosting ratio programs.
Ratio boosting in a website  doesnt happen in a short time tracker will ban the user.
The torrent service i am using is very hard to maintain...

**Comment by flightcrank** [comment]
yeah i did make an android version. Surprisingly since its all in java all the back end systems compiled and ran correctly with no change, pretty cool.

what tracker ? Theres no way for the tracker to tell if your using a desktop or android. It all faked in my program for the peer_id to the client header.

**Comment by KZTanvir** [comment]
Its not only cool. Its super.
No I meant ..there is a ratio booster for android that can boost but its old...and some problem with stopped .The tracker can notice the swarm speed .latest software in pc have the feature to change the speed randomly in a range.name is mratio or so. doesn't support that much of clients and too old.
And by trackers I meant the admins :p///

**Comment by flightcrank** [comment]
yeah uploading within a range is easy to do and trivial, however the final amount uploaded just gets sent to the tracker every 30mins. its called the update interval. So the tacker only gets sent one upload amount every 30mins. So i never bothered implementing a 'range' as its pretty pointless.

I may release the android version, but in all honestly its not really needed. I mean who needs to maintain a good ratio 'on the go' on a phone. Just use your desktop. There also also problems with battery life and the program needs to constantly run even when in the background, and there are issues with doing that on a phone.

**Comment by KZTanvir** [comment]
Yeah youre right.
But still there will be an option for android.
And thanks for the ratio boost. 💗
