### ISSUE TITLE
JRatioBoost do not download, but only upload the stats !

### ISSUE THREAD

**Issue by shahwaliullah** [flightcrank/JRatioBoost#7]
hi,
jratio boost, should downoad and upload at same time, like rati0 master or mrati0.

i tried this but it only upload.
plz fix issue or add this feature.

**Comment by flightcrank** [comment]
As you can see by the screenshot it did have this feature as it is not needed. Just download whatever you want with your regular torrent client. Then when you want to fake the uploads for it, just open the same torrent in JRatioBoost to fake the uploads for it.

the download feature was removed, as it is not needed.

**Comment by shahwaliullah** [comment]
if we download a torrent in real client, for example there we 10 or more leechers, but when our download completed, Leechers goes to 1 or 0, how can we upload? not every body has good internet especially Asian users,
if torrent is from scene, then this tool will be ok, as scenes contents are everywhere on public, private trackers, but if torrents are internal encodes or remux, how can we use this tool?

i think, you should enable download option,
even this is open source, not everybody is genius, i tried to compile an other opensource similar tool, which coder uploaded only source code in github, but i failed to compile it.

**Comment by flightcrank** [comment]
`if we download a torrent in real client, for example there were 10 or more leechers, but when our download completed, Leechers goes to 1 or 0`

thats just plain incorrect. that dose not happen. JRatioBoost reports ever usery as being a seeder with 100% downloaded.

`if torrent is from scene, then this tool will be ok, as scenes contents are everywhere on public, private trackers, but if torrents are internal encodes or remux, how can we use this tool?`

it does what it says on the box. It reports to the torrent tracker that you are uploading any torrent at the specified download rate. nothing more.

`i think, you should enable download option,`

No. Its pointless, downloading gives you a poor ratio. The purpose of this program is to spoof uploads. So thats what it does. The code is open source. feel free to fork your own version to enable that functionality.
`
even this is open source, not everybody is genius, i tried to compile an other opensource similar tool, which coder uploaded only source code in github, but i failed to compile it.`

Compilation instructions are given in the README file. No need to be a genius. Just follow the instructions
