### ISSUE TITLE
Add more torrent clients in JRatio 

### ISSUE THREAD

**Issue by shahwaliullah** [flightcrank/JRatioBoost#9]
Add more torrent clients in JRatio like:

rTorrent 0.9.7-0.13.7

Deluge 1.3.15
Deluge 2.0.3

qBittorrent 4.2.3
qBittorrent 4.3.9
and latest version

uTorrent 2.2.1.25130
uTorrent 2.2.1.25302

Transmission 2.92

i know i mentioned some are old version, but are popular torrent clients.

**Comment by flightcrank** [comment]
> Add more torrent clients in JRatio like:

Just select custion client and put in any version number you want. this has been a solved problem for a while.

**Comment by shahwaliullah** [comment]
ok, thanks.

but how to add deluge there, as list is not showing it.
